### ISSUE TITLE
关于DPO是InfoNCA的推导

### ISSUE THREAD

**Issue by yata0** [thu-ml/Noise-Contrastive-Alignment#2]
![image](https://github.com/thu-ml/Noise-Contrastive-Alignment/assets/29161726/a72f5fc2-cafb-4b4d-97c9-a7b2c8317665)
这中间的 $\alpha$ 不是简单的reward temperature，他的来源是KL惩罚的系数，推导中使这个值变为0，岂不是就是完全去掉了KL的惩罚，这个和DPO的含义完全就变了吧。
这是我对论文中该部分的一点疑问，希望能得到作者的解答，谢谢！

**Comment by ChenDRAG** [comment]
感谢关注。这个问题很深刻。KL惩罚的系数可以用两种具体手段体现在训练设计中。
1. DPO中的beta参数，体现在implicit reward计算时候乘的系数，它对训练中影响的是f_\theta的定义。
2. InfoNCA中的alpha，体现在对reward直接进行线性scale。reward是某种soft preference, 其soft程度由alpha影响

从维度2来看，DPO就是InfoNCA的特例。而因为DPO不处理reward setting，它体现KL系数只能通过方法一实现。而对于InfoNCA，为了和已有理论consistent，InfoNCA中alpha和beta的手段都使用了，InfoNCA在alpha=0时依然可以像DPO一样调节beta影响KL系数。

也可以换个视角，从更加数值的角度来看这件事：
DPO调节beta参数从工程角度是有效的，但从理论视角beta这个参数处于alpha=0奇点，有不合理处。因为理想情况下，在模型训练到收敛之后，对于DPO model其implicit reward（data logp ratio）就是应该趋向于正无穷或者负无穷。而在无穷上乘一个线性系数还是无穷。beta会产生实际作用本质上是因为在实际应用中我们implicit reward出于模型结构和训练时间的限制并不会绝对收敛到无穷，所以beta empirically才是有意义的。（可能有点绕，希望多少能make sense）

**Comment by NatureGeorge** [comment]
看起来InfoNCA即为[EXO](https://arxiv.org/abs/2402.00856)论文中的dpo-rw (equation 19)。也许forward KL和reverse KL可以交替训练一下看看能不能更好地match上soft labels。

> Towards Efficient Exact Optimization of Language Model Alignment
[Haozhe Ji](https://arxiv.org/search/cs?searchtype=author&query=Ji,+H), [Cheng Lu](https://arxiv.org/search/cs?searchtype=author&query=Lu,+C), [Yilin Niu](https://arxiv.org/search/cs?searchtype=author&query=Niu,+Y), [Pei Ke](https://arxiv.org/search/cs?searchtype=author&query=Ke,+P), [Hongning Wang](https://arxiv.org/search/cs?searchtype=author&query=Wang,+H), [Jun Zhu](https://arxiv.org/search/cs?searchtype=author&query=Zhu,+J), [Jie Tang](https://arxiv.org/search/cs?searchtype=author&query=Tang,+J), [Minlie Huang](https://arxiv.org/search/cs?searchtype=author&query=Huang,+M)
