### ISSUE TITLE
Any plan for open source?

### ISSUE THREAD

**Issue by hzy312** [thu-ml/Noise-Contrastive-Alignment#3]
有计划开源吗？

**Comment by ChenDRAG** [comment]
@hzy312 Hi, sorry for the late reply. The code and training script are released. If you are only interested in the binary preference version of  NCA, it is also supported by the official trl library now (By setting `loss_type` to `nca_pair` in `DPOTrainer`).
https://github.com/huggingface/trl/blob/cd85b14fbbaf7e4d9b01ef8ec19655666af20047/trl/trainer/dpo_trainer.py#L1135
